---
name: nginx

director_uuid: beb2169f-8911-453f-98ed-978adcb168c2 # FIXME you put Director's UUID


instance_groups:
- name: nginx
  instances: 1
  vm_type: t2.micro
  persistent_disk_type: nginx
  stemcell: centos
  networks:
  - name: vip
    # FIXME: replace the IP address with your Elastic IP
    # the Elastic IP must have scope 'vpc' not 'standard'
    static_ips: [ 52.23.10.10 ] # FIXME replace with your public IP
  - name: dynamic
    default: [ dns, gateway ]
  jobs:
  - name: nginx
    release: nginx
    properties:
      nginx_conf: |
        worker_processes  1;
        error_log /var/vcap/sys/log/nginx/error.log   info;
        #pid        logs/nginx.pid; # PIDFILE is configured via monit's ctl
        events {
          worker_connections  1024;
        }
        http {
          include /var/vcap/packages/nginx/conf/mime.types;
          default_type  application/octet-stream;
          sendfile        on;
          keepalive_timeout  65;
          server_names_hash_bucket_size 64;
          # redirect HTTP to HTTPS
          server {
            server_name _; # invalid value which will never trigger on a real hostname.
            listen 80;
            # FIXME: replace all occurrences of 'www.nono.io' with your server's FQDN
            rewrite ^ https://www.nono.io$request_uri?;
            access_log /var/vcap/sys/log/nginx/www.nono.io-access.log;
            error_log /var/vcap/sys/log/nginx/www.nono.io-error.log;
          }
          server {
            server_name www.nono.io;
            # weak DH https://weakdh.org/sysadmin.html
            ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
            ssl_prefer_server_ciphers on;
            # poodle https://scotthelme.co.uk/sslv3-goes-to-the-dogs-poodle-kills-off-protocol/
            ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
            listen              443 ssl;
            ssl_certificate     /var/vcap/jobs/nginx/etc/ssl_chained.crt.pem;
            ssl_certificate_key /var/vcap/jobs/nginx/etc/ssl.key.pem;
            access_log /var/vcap/sys/log/nginx/www.nono.io-access.log;
            error_log /var/vcap/sys/log/nginx/www.nono.io-error.log;
            root /var/vcap/store/nginx/www/document_root;
            index index.shtml index.html index.htm;
          }
        }
      pre_start: |
        #!/bin/bash -ex
        NGINX_DIR=/var/vcap/store/nginx
        if [ ! -d $NGINX_DIR ]; then
          mkdir -p $(basename $NGINX_DIR)
          cd $(basename $NGINX_DIR)
          curl -L https://github.com/cunnie/sslip.io/archive/v1.tar.gz |
            tar xzf -
          mv sslip.io-1 $NGINX_DIR
          chown -R vcap:vcap $NGINX_DIR
        fi
      # FIXME: replace with your HTTPS SSL key
      ssl_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIJKgIBAAKCAgEAqgBtwWIXLHyXqxul7PUVV55qku+yVwbKSHKYtREXYY0i38x6
        myM8C98VsfoEq1P6QQluTHTKau+VysdPjXLz7t5mG1k6yBPitiszdTChGh+iHg==
        -----END RSA PRIVATE KEY-----
      # FIXME: replace with your HTTPS SSL chained certificate
      ssl_chained_cert: |
        -----BEGIN CERTIFICATE-----
        MIIGYTCCBUmgAwIBAgIRAOFIqgO1kqC+5E0ef2cqXbMwDQYJKoZIhvcNAQELBQAw
        c2RwQdk=
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIGCDCCA/CgAwIBAgIQKy5u6tl1NmwUim7bo3yMBzANBgkqhkiG9w0BAQwFADCB
        +AZxAeKCINT+b72x
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIFdDCCBFygAwIBAgIQJ2buVutJ846r13Ci/ITeIjANBgkqhkiG9w0BAQwFADBv
        pu/xO28QOG8=
        -----END CERTIFICATE-----

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

stemcells:
- alias: centos
  os: centos-7
  version: latest

releases:
- name: nginx
  version: latest
