azs:
- name: z1
  cloud_properties:
    availability_zone: us-east-1a

vm_types:
- name: t2.micro.100G
  cloud_properties:
    instance_type: t2.micro
    availability_zone: us-east-1a
    ephemeral_disk:
      size: 100_000
      type: gp2

disk_types:
- name: nginx
  disk_size: 5_120
  cloud_properties:
    type: gp2

networks:
- name: dynamic
  type: dynamic
  cloud_properties:
    subnet: subnet-1c90ef6b # FIXME: replace with your subnet
- name: vip
  type: vip

compilation:
  workers: 1
  reuse_compilation_vms: true
  vm_type: c4.large
  network: dynamic

properties:
  aws:
    default_security_groups: [bosh]
