---
name: nginx

resource_pools:
- name: nginx_pool
  network: default
  cloud_properties:
    instance_type: t2.micro
    ephemeral_disk:
      size: 4000
      type: gp2
    availability_zone: us-east-1a
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-centos-7-go_agent?v=3058
    sha1: 757c23269dfb1f2706e39d696ea06aa6c4e9ef38

jobs:
- name: nginx
  instances: 1
  templates:
  - { release: nginx, name: nginx }
  resource_pool: nginx_pool
  networks:
  - name: vip
    # FIXME: replace the IP address with your Elastic IP
    # the Elastic IP must have scope 'vpc' not 'standard'
    static_ips: [52.0.76.229]
  - name: default
  properties:
    nginx_conf: |
      worker_processes  1;
      error_log /var/vcap/sys/log/nginx/error.log   info;
      #pid        logs/nginx.pid; # PIDFILE is configured via monit's ctl
      events {
        worker_connections  1024;
      }
      http {
        include /var/vcap/packages/nginx/conf/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
        server_names_hash_bucket_size 64;
        # redirect HTTP to HTTPS
        server {
          listen 80;
          access_log /var/vcap/sys/log/nginx/sslip.io-access.log;
          error_log /var/vcap/sys/log/nginx/sslip.io-error.log;
        }
      }

networks:
- name: default
  type: dynamic
  cloud_properties:
    # FIXME: replace the subnet with your subnet-id
    subnet: subnet-1c90ef6b
- name: vip
  type: vip

cloud_provider:
  template: {name: cpi, release: bosh-aws-cpi}

  ssh_tunnel:
    # FIXME: replace the IP address with your Elastic IP
    host: 52.0.76.229
    port: 22
    user: vcap
    # FIXME: replace with the pathname of your downloaded AWS Key Pair
    # (Power users: no passphrase-protection otherwise you'll see a
    # `asn1: structure error: tags don't match` message when deploying
    private_key: /Users/cunnie/.ssh/aws_nono.pem

  # FIXME: replace 'dmitriy' with a secure password
  mbus: https://nats:dmitriy@52.0.76.229:6868

  properties:
    aws:
      # FIXME: replace with your AWS Access Key
      access_key_id: AKIAxxxxxxxxxxxxxxxx
      # FIXME: replace with your AWS Secret
      secret_access_key: 0+B1XW6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      # FIXME: replace with your AWS Key Pair name
      default_key_name: aws_nono
      # FIXME: replace with your security group
      # the Security Group MUST have the VPC ID of your VPC (e.g. 'vpc-e4250881')
      default_security_groups: [no-filter-vpc]
      region: us-east-1

    # FIXME: replace 'dmitriy' with a secure password
    agent: {mbus: "https://nats:dmitriy@0.0.0.0:6868"}

    blobstore:
      provider: local
      path: /var/vcap/micro_bosh/data/cache

    ntp: [0.north-america.pool.ntp.org]

releases:
  - name: nginx
    url: https://s3.amazonaws.com//nginx-release/nginx-2.tgz
    sha1: 667cc1a0f9117bdb4b217ee2b76dc20e61371c02
  - name: bosh-aws-cpi
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=28
    sha1: c7ce03393ebedd87a860dc609758ddb9654360fa
